name: CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      pack ./peoplehr
            - name: Ballerina Test
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      test --code-coverage ./peoplehr
              env:
                BASE_URL: ${{ secrets.BASE_URL }}
                API_KEY: ${{ secrets.API_KEY }}
                EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
                PASSWORD: ${{ secrets.PASSWORD }}
                QUERY_NAME: ${{ secrets.QUERY_NAME }}
            
            # Read the ballerina test results
            - name: Read Ballerina Test Results
              id: test_results
              run: |
                content=`cat ./peoplehr/target/report/test_results.json`                
                content="${content//'%'/'%25'}"
                content="${content//$'\n'/'%0A'}"
                content="${content//$'\r'/'%0D'}"
                echo "::set-output name=testResultsJson::$content"
            # Print the code coverage information
            - name: Code Coverage
              run: |
                echo "Covered Code Lines : ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}}"
                echo "Total Code Lines : $(expr ${{fromJson(steps.test_results.outputs.testResultsJson).missedLines}} + ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}})"
                echo "Code Coverage Percentage : ${{fromJson(steps.test_results.outputs.testResultsJson).coveragePercentage}}"
